"use client" 
import Auth from '@/app/component/Auth/Auth'
import Header from '@/app/component/Header/Header'
import SettingsProfile from '@/app/component/settingProfile/settingsProfile'

import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body>

          {children}
          <Header />
          <SettingsProfile />

      </body>
    </html>
  )
}
