"use client" 
import './globals.css'
import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'
import Header from './component/Header/Header'

import Panel from './component/panel/Panel'
import { Provider } from 'react-redux'
import { store } from './component/store/store'
import Auth from './component/Auth/Auth'
import React, { useState, useEffect } from 'react';
import { getToken, isAuth } from './component/store/token'
import SettingsProfile from './component/settingProfile/settingsProfile'

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //console.log(localStorage.getItem('token'))

  const [isOpen, setIsOpen] = useState(false)
  const [isOpen1, setIsOpen1] = useState(false)
  console.log(isOpen)
  useEffect(()=>{
   setTimeout (() => {if (isAuth() && getToken() !== "undefined" ) {
      return setIsOpen1(true)
    } else {
      return setIsOpen1(false)
    }},500)
  },[isOpen])

  return (
    <html lang="en">
      <body>
        <Provider store={store}>

          <Header/>
          {children}
          
          {//isOpen1 ? <Panel isOpen={isOpen} /> : <Auth toggle={setIsOpen} isOpen={isOpen}  />  
          }
        </Provider>
      </body>
    </html>
  )
}
