"use client" 
import './globals.css'
import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'
import Header from './component/Header/Header'

import Panel from './component/panel/Panel'
import { Provider } from 'react-redux'
import { store } from './component/store/store'
import Auth from './component/Auth/Auth'
import React, { useState, useEffect } from 'react';

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //console.log(localStorage.getItem('token'))
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <div>
            UI To Do
          </div>
          <Header />
          {children}
          {true ? <Auth /> :  <Panel/> }
        </Provider>
      </body>
    </html>
  )
}
