"use client" 
import Header from '@/app/component/Header/Header'
import Panel from '@/app/component/panel/Panel'
import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //console.log(localStorage.getItem('token'))



  return (
    <html lang="en">
      <body>

          {children}
          <Header />
          <Panel/>

      </body>
    </html>
  )
}
